---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.3
  name: clusterpolicyendpoints.networking.k8s.aws
spec:
  group: networking.k8s.aws
  names:
    kind: ClusterPolicyEndpoint
    listKind: ClusterPolicyEndpointList
    plural: clusterpolicyendpoints
    shortNames:
    - cpe
    singular: clusterpolicyendpoint
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterPolicyEndpoint is the Schema for the clusterpolicyendpoints
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ClusterPolicyEndpointSpec defines the desired state of ClusterPolicyEndpoint
            properties:
              egress:
                description: Egress is the list of egress rules containing resolved
                  network addresses
                items:
                  description: ClusterEndpointInfo defines the network endpoint information
                    for the cluster policy ingress/egress
                  properties:
                    action:
                      description: Action from the CNP rule
                      enum:
                      - Accept
                      - Deny
                      - Pass
                      type: string
                    cidr:
                      description: CIDR is the network address(s) of the endpoint
                      type: string
                    domainName:
                      description: DomainName is the FQDN for the endpoint (egress-only)
                      pattern: ^(\*\.)?([a-zA-z0-9]([-a-zA-Z0-9_]*[a-zA-Z0-9])?\.)+[a-zA-z0-9]([-a-zA-Z0-9_]*[a-zA-Z0-9])?\.?$
                      type: string
                    ports:
                      description: Ports is the list of ports
                      items:
                        description: Port contains information about the transport
                          port/protocol
                        properties:
                          endPort:
                            description: |-
                              Endport specifies the port range port to endPort
                              port must be defined and an integer, endPort > port
                            format: int32
                            type: integer
                          port:
                            description: Port specifies the numerical port for the
                              protocol. If empty applies to all ports
                            format: int32
                            type: integer
                          protocol:
                            default: TCP
                            description: Protocol specifies the transport protocol,
                              default TCP
                            type: string
                        type: object
                      type: array
                  required:
                  - action
                  type: object
                type: array
              ingress:
                description: Ingress is the list of ingress rules containing resolved
                  network addresses
                items:
                  description: ClusterEndpointInfo defines the network endpoint information
                    for the cluster policy ingress/egress
                  properties:
                    action:
                      description: Action from the CNP rule
                      enum:
                      - Accept
                      - Deny
                      - Pass
                      type: string
                    cidr:
                      description: CIDR is the network address(s) of the endpoint
                      type: string
                    domainName:
                      description: DomainName is the FQDN for the endpoint (egress-only)
                      pattern: ^(\*\.)?([a-zA-z0-9]([-a-zA-Z0-9_]*[a-zA-Z0-9])?\.)+[a-zA-z0-9]([-a-zA-Z0-9_]*[a-zA-Z0-9])?\.?$
                      type: string
                    ports:
                      description: Ports is the list of ports
                      items:
                        description: Port contains information about the transport
                          port/protocol
                        properties:
                          endPort:
                            description: |-
                              Endport specifies the port range port to endPort
                              port must be defined and an integer, endPort > port
                            format: int32
                            type: integer
                          port:
                            description: Port specifies the numerical port for the
                              protocol. If empty applies to all ports
                            format: int32
                            type: integer
                          protocol:
                            default: TCP
                            description: Protocol specifies the transport protocol,
                              default TCP
                            type: string
                        type: object
                      type: array
                  required:
                  - action
                  type: object
                type: array
              podSelectorEndpoints:
                description: |-
                  PodSelectorEndpoints contains information about the pods
                  matching the policy across all namespaces
                items:
                  description: PodEndpoint defines the summary information for the
                    pods
                  properties:
                    hostIP:
                      description: HostIP is the IP address of the host the pod is
                        currently running on
                      type: string
                    name:
                      description: Name is the pod name
                      type: string
                    namespace:
                      description: Namespace is the pod namespace
                      type: string
                    podIP:
                      description: PodIP is the IP address of the pod
                      type: string
                  required:
                  - hostIP
                  - name
                  - namespace
                  - podIP
                  type: object
                type: array
              policyRef:
                description: PolicyRef is a reference to the Kubernetes ClusterNetworkPolicy
                  resource.
                properties:
                  name:
                    description: Name is the name of the ClusterNetworkPolicy
                    type: string
                required:
                - name
                type: object
              priority:
                description: Priority from the CNP
                format: int32
                type: integer
              tier:
                description: Tier from the CNP
                enum:
                - Admin
                - Baseline
                type: string
            required:
            - policyRef
            - priority
            - tier
            type: object
          status:
            description: ClusterPolicyEndpointStatus defines the observed state of
              ClusterPolicyEndpoint
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
